[package]
name = "bunbun"
version = "1.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
colored = "2.1.0"
sysinfo = "0.30.7"
whoami = "1.5.1"

[profile.release]
strip = true # Strip debug symbols
opt-level = "z" # Optimise for size
lto = true # Enable link type optimisation
codegen-units = 1 # Reduce parallel code generation units
panic = "abort" # Abort on panic!
